export const MOVIE = [
    {
        adult: false,
        backdrop_path: "/path1.jpg",
        genre_ids: [1, 2, 3],
        id: 1,
        original_language: "es",
        original_title: "Película 1",
        overview: "Descripción de la película 1",
        popularity: 8.5,
        poster_path: "/proyecto-final-diri/images/stab.jpg",
        release_date: new Date("2019-08-15"),
        title: "Stab",
        video: false,
        vote_average: 7.5,
        vote_count: 1000
    },
    {
        adult: false,
        backdrop_path: "/path2.jpg",
        genre_ids: [2, 3, 4],
        id: 2,
        original_language: "en",
        original_title: "Movie 2",
        overview: "Description of movie 2",
        popularity: 7.8,
        poster_path: "/proyecto-final-diri/images/stab.jpg",
        release_date: new Date("2020-12-03"),
        title: "Beyond the Stars",
        video: false,
        vote_average: 8.0,
        vote_count: 1200
    },
    {
        adult: false,
        backdrop_path: "/path3.jpg",
        genre_ids: [1, 4],
        id: 3,
        original_language: "fr",
        original_title: "Film 3",
        overview: "Description du film 3",
        popularity: 6.9,
        poster_path: "/proyecto-final-diri/images/stab.jpg",
        release_date: new Date("2021-04-22"),
        title: "Echoes of Tomorrow",
        video: false,
        vote_average: 6.5,
        vote_count: 800
    },
    {
        adult: false,
        backdrop_path: "/path4.jpg",
        genre_ids: [2, 5],
        id: 4,
        original_language: "it",
        original_title: "Film 4",
        overview: "Descrizione del film 4",
        popularity: 7.2,
        poster_path: "/proyecto-final-diri/images/stab.jpg",
        release_date: new Date("2022-11-08"),
        title: "The Last Cipher",
        video: false,
        vote_average: 7.8,
        vote_count: 950
    },
    {
        adult: false,
        backdrop_path: "/path5.jpg",
        genre_ids: [3, 5],
        id: 5,
        original_language: "de",
        original_title: "Film 5",
        overview: "Beschreibung von Film 5",
        popularity: 8.1,
        poster_path: "/proyecto-final-diri/images/stab.jpg",
        release_date: new Date("2023-02-14"),
        title: "Whispers in the Wind",
        video: false,
        vote_average: 8.2,
        vote_count: 1100
    }
]